"""Add hashed_password to usuario

Revision ID: 1cc0fa99ddbd
Revises: 7e1cd3f60a86
Create Date: 2025-04-21 15:07:56.475914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc0fa99ddbd'
down_revision: Union[str, None] = '7e1cd3f60a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'hashed_password')
    # ### end Alembic commands ###
