"""mejoras en orden de compra, agrangando la escalabilidada a mas items

Revision ID: 3e141d8bd6d7
Revises: abf70bffaa73
Create Date: 2025-05-15 09:14:49.748890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e141d8bd6d7'
down_revision: Union[str, None] = 'abf70bffaa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_items',
    sa.Column('id_item', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('id_orden_compra', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad_medida', sa.String(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_orden_compra'], ['ordenes_compra.id_orden_compra'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    op.create_index(op.f('ix_orden_items_id_item'), 'orden_items', ['id_item'], unique=False)
    op.drop_column('ordenes_compra', 'unidad_ejecutora')
    op.drop_column('ordenes_compra', 'tipo_combustible')
    op.drop_column('ordenes_compra', 'cantidad')
    op.drop_column('ordenes_compra', 'tipo_contrato')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_compra', sa.Column('tipo_contrato', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ordenes_compra', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ordenes_compra', sa.Column('tipo_combustible', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ordenes_compra', sa.Column('unidad_ejecutora', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orden_items_id_item'), table_name='orden_items')
    op.drop_table('orden_items')
    # ### end Alembic commands ###
