"""mejoras en orden de compra, agrangando la escalabilidada a mas items 333

Revision ID: 542220235348
Revises: 3e141d8bd6d7
Create Date: 2025-05-15 11:12:20.659290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542220235348'
down_revision: Union[str, None] = '3e141d8bd6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden_items', sa.Column('tipo_combustible', sa.String(), nullable=False))
    op.drop_column('orden_items', 'descripcion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orden_items', sa.Column('descripcion', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('orden_items', 'tipo_combustible')
    # ### end Alembic commands ###
