"""Initial migration render

Revision ID: 9937c8caf40e
Revises: 
Create Date: 2025-04-30 15:41:42.644597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9937c8caf40e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('nombre_cliente', sa.String(), nullable=False),
    sa.Column('direccion_cliente', sa.String(), nullable=False),
    sa.Column('ruc_cliente', sa.String(), nullable=False),
    sa.Column('telefono_cliente', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('ruc_cliente')
    )
    op.create_index(op.f('ix_clientes_id_cliente'), 'clientes', ['id_cliente'], unique=False)
    op.create_table('subastas',
    sa.Column('id_subasta', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('cantidad_requerida', sa.Integer(), nullable=False),
    sa.Column('codigo_subasta', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('lugar_entrega', sa.String(), nullable=False),
    sa.Column('numero_entregas', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_subasta'),
    sa.UniqueConstraint('codigo_subasta')
    )
    op.create_index(op.f('ix_subastas_id_subasta'), 'subastas', ['id_subasta'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('nombre_usuario', sa.String(), nullable=False),
    sa.Column('cargo_usuario', sa.String(), nullable=False),
    sa.Column('correo_usuario', sa.String(), nullable=False),
    sa.Column('domicilio_usuario', sa.String(), nullable=False),
    sa.Column('telefono_usuario', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('nombre_usuario'),
    sa.UniqueConstraint('telefono_usuario')
    )
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('contratos',
    sa.Column('id_contrato', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('fecha_firma', sa.Date(), nullable=False),
    sa.Column('estado_contrato', sa.String(), nullable=False),
    sa.Column('monto_total_contrato', sa.Float(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_subasta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_subasta'], ['subastas.id_subasta'], ),
    sa.PrimaryKeyConstraint('id_contrato')
    )
    op.create_index(op.f('ix_contratos_id_contrato'), 'contratos', ['id_contrato'], unique=False)
    op.create_table('documentacion',
    sa.Column('id_documentacion', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('nombre_documento', sa.String(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=False),
    sa.Column('fecha_subida', sa.Date(), nullable=False),
    sa.Column('id_subasta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_subasta'], ['subastas.id_subasta'], ),
    sa.PrimaryKeyConstraint('id_documentacion')
    )
    op.create_index(op.f('ix_documentacion_id_documentacion'), 'documentacion', ['id_documentacion'], unique=False)
    op.create_table('registros_visitas',
    sa.Column('id_registro_visita', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('fecha_visita', sa.Date(), nullable=False),
    sa.Column('motivo_visita', sa.String(), nullable=False),
    sa.Column('resultado_visita', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_registro_visita')
    )
    op.create_index(op.f('ix_registros_visitas_id_registro_visita'), 'registros_visitas', ['id_registro_visita'], unique=False)
    op.create_table('ordenes_compra',
    sa.Column('id_orden_compra', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('codigo_siga', sa.String(), nullable=False),
    sa.Column('fecha_emision_oc', sa.Date(), nullable=False),
    sa.Column('tipo_compra', sa.String(), nullable=False),
    sa.Column('lugar_entrega_oc', sa.String(), nullable=False),
    sa.Column('estado_oc', sa.String(), nullable=False),
    sa.Column('monto_total_oc', sa.Float(), nullable=False),
    sa.Column('id_contrato', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_contrato'], ['contratos.id_contrato'], ),
    sa.PrimaryKeyConstraint('id_orden_compra'),
    sa.UniqueConstraint('codigo_siga')
    )
    op.create_index(op.f('ix_ordenes_compra_id_orden_compra'), 'ordenes_compra', ['id_orden_compra'], unique=False)
    op.create_table('actas_custodias',
    sa.Column('id_actas_custodias', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('cantidad_custodia', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('responsable', sa.String(), nullable=False),
    sa.Column('fecha_firma_custodia', sa.Date(), nullable=False),
    sa.Column('id_orden_compra', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_orden_compra'], ['ordenes_compra.id_orden_compra'], ),
    sa.PrimaryKeyConstraint('id_actas_custodias')
    )
    op.create_index(op.f('ix_actas_custodias_id_actas_custodias'), 'actas_custodias', ['id_actas_custodias'], unique=False)
    op.create_table('entregas',
    sa.Column('id_entrega', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('cantidad_entregada', sa.Float(), nullable=False),
    sa.Column('estado_entrega', sa.String(), nullable=False),
    sa.Column('id_orden_compra', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_orden_compra'], ['ordenes_compra.id_orden_compra'], ),
    sa.PrimaryKeyConstraint('id_entrega')
    )
    op.create_index(op.f('ix_entregas_id_entrega'), 'entregas', ['id_entrega'], unique=False)
    op.create_table('vales_consumo',
    sa.Column('id_vale_consumo', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('cantidad_consumida', sa.Float(), nullable=False),
    sa.Column('descripcion_vale', sa.String(), nullable=False),
    sa.Column('id_orden_compra', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_orden_compra'], ['ordenes_compra.id_orden_compra'], ),
    sa.PrimaryKeyConstraint('id_vale_consumo')
    )
    op.create_index(op.f('ix_vales_consumo_id_vale_consumo'), 'vales_consumo', ['id_vale_consumo'], unique=False)
    op.create_table('facturas',
    sa.Column('id_factura', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('numero_factura', sa.String(), nullable=False),
    sa.Column('fecha_emision_factura', sa.Date(), nullable=False),
    sa.Column('monto_total_factura', sa.Float(), nullable=False),
    sa.Column('estado_factura', sa.String(), nullable=False),
    sa.Column('id_entrega', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ),
    sa.PrimaryKeyConstraint('id_factura'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_index(op.f('ix_facturas_id_factura'), 'facturas', ['id_factura'], unique=False)
    op.create_table('guias_remision',
    sa.Column('id_guia_remision', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('numero_guia', sa.String(), nullable=False),
    sa.Column('fecha_emision_guia', sa.Date(), nullable=False),
    sa.Column('lugar_salida', sa.String(), nullable=False),
    sa.Column('lugar_entrega_guia', sa.String(), nullable=False),
    sa.Column('dni_conductor', sa.String(), nullable=False),
    sa.Column('placa_vehiculo_guia', sa.String(), nullable=False),
    sa.Column('estado_guia', sa.String(), nullable=False),
    sa.Column('id_entrega', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ),
    sa.PrimaryKeyConstraint('id_guia_remision'),
    sa.UniqueConstraint('numero_guia')
    )
    op.create_index(op.f('ix_guias_remision_id_guia_remision'), 'guias_remision', ['id_guia_remision'], unique=False)
    op.create_table('logistica_transport',
    sa.Column('id_logistica_transport', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('placa_vehiculo_logistica', sa.String(), nullable=False),
    sa.Column('estado_logistica', sa.String(), nullable=False),
    sa.Column('id_entrega', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_logistica_transport')
    )
    op.create_index(op.f('ix_logistica_transport_id_logistica_transport'), 'logistica_transport', ['id_logistica_transport'], unique=False)
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto_pagado', sa.Float(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id_factura'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_index(op.f('ix_pagos_id_pago'), 'pagos', ['id_pago'], unique=False)
    op.create_table('seguimiento_pagos',
    sa.Column('id_seguimiento_pago', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('estado_pago', sa.String(), nullable=False),
    sa.Column('motivo_retraso', sa.String(), nullable=False),
    sa.Column('observaciones_pago', sa.String(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('id_registro_visita', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['facturas.id_factura'], ),
    sa.ForeignKeyConstraint(['id_registro_visita'], ['registros_visitas.id_registro_visita'], ),
    sa.PrimaryKeyConstraint('id_seguimiento_pago')
    )
    op.create_index(op.f('ix_seguimiento_pagos_id_seguimiento_pago'), 'seguimiento_pagos', ['id_seguimiento_pago'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguimiento_pagos_id_seguimiento_pago'), table_name='seguimiento_pagos')
    op.drop_table('seguimiento_pagos')
    op.drop_index(op.f('ix_pagos_id_pago'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_logistica_transport_id_logistica_transport'), table_name='logistica_transport')
    op.drop_table('logistica_transport')
    op.drop_index(op.f('ix_guias_remision_id_guia_remision'), table_name='guias_remision')
    op.drop_table('guias_remision')
    op.drop_index(op.f('ix_facturas_id_factura'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_vales_consumo_id_vale_consumo'), table_name='vales_consumo')
    op.drop_table('vales_consumo')
    op.drop_index(op.f('ix_entregas_id_entrega'), table_name='entregas')
    op.drop_table('entregas')
    op.drop_index(op.f('ix_actas_custodias_id_actas_custodias'), table_name='actas_custodias')
    op.drop_table('actas_custodias')
    op.drop_index(op.f('ix_ordenes_compra_id_orden_compra'), table_name='ordenes_compra')
    op.drop_table('ordenes_compra')
    op.drop_index(op.f('ix_registros_visitas_id_registro_visita'), table_name='registros_visitas')
    op.drop_table('registros_visitas')
    op.drop_index(op.f('ix_documentacion_id_documentacion'), table_name='documentacion')
    op.drop_table('documentacion')
    op.drop_index(op.f('ix_contratos_id_contrato'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_subastas_id_subasta'), table_name='subastas')
    op.drop_table('subastas')
    op.drop_index(op.f('ix_clientes_id_cliente'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
