"""mejorar atributos de factura para enlazar a sunat

Revision ID: abf70bffaa73
Revises: facbc5b9ffb6
Create Date: 2025-05-14 16:13:56.548584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf70bffaa73'
down_revision: Union[str, None] = 'facbc5b9ffb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('descripcion_item', sa.String(), nullable=False))
    op.add_column('facturas', sa.Column('unidad_medida', sa.String(), nullable=False))
    op.add_column('facturas', sa.Column('cantidad', sa.Float(), nullable=False))
    op.add_column('facturas', sa.Column('valor_unitario', sa.Float(), nullable=False))
    op.add_column('facturas', sa.Column('precio_unitario', sa.Float(), nullable=False))
    op.add_column('facturas', sa.Column('igv', sa.Float(), nullable=False))
    op.add_column('facturas', sa.Column('moneda', sa.String(), nullable=False))
    op.add_column('facturas', sa.Column('tipo_de_igv', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'tipo_de_igv')
    op.drop_column('facturas', 'moneda')
    op.drop_column('facturas', 'igv')
    op.drop_column('facturas', 'precio_unitario')
    op.drop_column('facturas', 'valor_unitario')
    op.drop_column('facturas', 'cantidad')
    op.drop_column('facturas', 'unidad_medida')
    op.drop_column('facturas', 'descripcion_item')
    # ### end Alembic commands ###
