"""add precio_unitario to entrega_items

Revision ID: c0730a40b458
Revises: 4181e94562dd
Create Date: 2025-05-17 14:18:12.288398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0730a40b458'
down_revision: Union[str, None] = '4181e94562dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entrega_items_id_item', table_name='entrega_items')
    op.drop_table('entrega_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrega_items',
    sa.Column('id_item', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('id_entrega', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo_combustible', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cantidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unidad_medida', sa.VARCHAR(), server_default=sa.text("'Galón US'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_entrega'], ['entregas.id_entrega'], name='entrega_items_id_entrega_fkey'),
    sa.PrimaryKeyConstraint('id_item', name='entrega_items_pkey')
    )
    op.create_index('ix_entrega_items_id_item', 'entrega_items', ['id_item'], unique=False)
    # ### end Alembic commands ###
