"""Agregar nuevos campos a OrdenCompra

Revision ID: c476b1c8da2f
Revises: 9937c8caf40e
Create Date: 2025-05-05 16:00:41.872480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c476b1c8da2f'
down_revision: Union[str, None] = '9937c8caf40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_compra', sa.Column('fecha_limite_entrega', sa.Date(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('cantidad', sa.Integer(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('numero_orden', sa.String(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('tipo_combustible', sa.String(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('tipo_contrato', sa.String(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('unidad_ejecutora', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes_compra', 'unidad_ejecutora')
    op.drop_column('ordenes_compra', 'tipo_contrato')
    op.drop_column('ordenes_compra', 'tipo_combustible')
    op.drop_column('ordenes_compra', 'numero_orden')
    op.drop_column('ordenes_compra', 'cantidad')
    op.drop_column('ordenes_compra', 'fecha_limite_entrega')
    # ### end Alembic commands ###
